// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe9o-bGKpSRkjJxnDyTGdpy9Fs70gUB58',
    appId: '1:650715563297:web:3f347c234847e1feeeea60',
    messagingSenderId: '650715563297',
    projectId: 'todoapp-67d02',
    authDomain: 'todoapp-67d02.firebaseapp.com',
    storageBucket: 'todoapp-67d02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2KQ-4WT8CF1Fv_7L9bJf5r8M-j8UvgrU',
    appId: '1:650715563297:android:ef59917d54f6efe5eeea60',
    messagingSenderId: '650715563297',
    projectId: 'todoapp-67d02',
    storageBucket: 'todoapp-67d02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE6BYjTWgx5H8xvBsv5hIjPjb4tN1iijk',
    appId: '1:650715563297:ios:406546c01784004aeeea60',
    messagingSenderId: '650715563297',
    projectId: 'todoapp-67d02',
    storageBucket: 'todoapp-67d02.firebasestorage.app',
    iosBundleId: 'com.example.try3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE6BYjTWgx5H8xvBsv5hIjPjb4tN1iijk',
    appId: '1:650715563297:ios:406546c01784004aeeea60',
    messagingSenderId: '650715563297',
    projectId: 'todoapp-67d02',
    storageBucket: 'todoapp-67d02.firebasestorage.app',
    iosBundleId: 'com.example.try3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe9o-bGKpSRkjJxnDyTGdpy9Fs70gUB58',
    appId: '1:650715563297:web:de0fc23c27b705daeeea60',
    messagingSenderId: '650715563297',
    projectId: 'todoapp-67d02',
    authDomain: 'todoapp-67d02.firebaseapp.com',
    storageBucket: 'todoapp-67d02.firebasestorage.app',
  );
}
